### ISSUE TITLE
local language BUG

### ISSUE THREAD

**Issue by rogerko1** [Manu098vm/Tera-Finder#15]
A bug where Pokémon cannot be found when using the local language

EX: Requested value 'Pokémon name' was not found

But the English name can

**Comment by scottwang0611** [comment]
me too

**Comment by Manu098vm** [comment]
What language are you guys using? Is it within the standalone app or pkhex plugin?
Please carefully describe how to reproduce the error.

**Comment by scottwang0611** [comment]
> 

System.ArgumentException: Requested value '暴鲤龙' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseUInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, UInt32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, UInt32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value)
   at TeraFinder.CalculatorForm.GetSpeciesAndForm() in e:\workspace\Tera-Finder\Forms\CalculatorForm.cs:line 198
   at TeraFinder.CalculatorForm.cmbSpecies_IndexChanged(Object sender, EventArgs e) in e:\workspace\Tera-Finder\Forms\CalculatorForm.cs:line 123
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by Manu098vm** [comment]
Solved in https://github.com/Manu098vm/Tera-Finder/commit/ac9c68d4a76aedefdf5e788d74579c922bcd66b9.
Let me know if you end up finding any other bug in ch localizations :)

**Comment by scottwang0611** [comment]
build fail
msg:
pkNX.Structures.FlatBuffers -> e:\workspace\Tera-Finder\pkNX.Structures.FlatBuffers\bin\Debug\net6.0\pkNX.Structures.FlatBuffers.dll
E:\workspace\Tera-Finder\obj\Debug\net6.0-windows\.NETCoreApp,Version=v6.0.AssemblyAttributes.cs(4,12): error CS0579: “global::System.Runtime.Versioning.TargetFramework

Attribute”特性重复 [e:\workspace\Tera-Finder\TeraFinder.csproj]
E:\workspace\Tera-Finder\obj\Debug\net6.0-windows\TeraFinder.AssemblyInfo.cs(13,12): error CS0579: “System.Reflection.AssemblyCompanyAttribute”特性重复 [e:\workspace\T
era-F
inder\TeraFinder.csproj]
E:\workspace\Tera-Finder\obj\Debug\net6.0-windows\TeraFinder.AssemblyInfo.cs(14,12): error CS0579: “System.Reflection.AssemblyConfigurationAttribute”特性重复 [e:\works
pace\
Tera-Finder\TeraFinder.csproj]
E:\workspace\Tera-Finder\obj\Debug\net6.0-windows\TeraFinder.AssemblyInfo.cs(16,12): error CS0579: “System.Reflection.AssemblyFileVersionAttribute”特性重复 [e:\workspa
ce\Te
ra-Finder\TeraFinder.csproj]
E:\workspace\Tera-Finder\obj\Debug\net6.0-windows\TeraFinder.AssemblyInfo.cs(17,12): error CS0579: “System.Reflection.AssemblyInformationalVersionAttribute”特性重复 [e
:\wor
kspace\Tera-Finder\TeraFinder.csproj]
E:\workspace\Tera-Finder\obj\Debug\net6.0-windows\TeraFinder.AssemblyInfo.cs(18,12): error CS0579: “System.Reflection.AssemblyProductAttribute”特性重复 [e:\workspace\T
era-F
inder\TeraFinder.csproj]
E:\workspace\Tera-Finder\obj\Debug\net6.0-windows\TeraFinder.AssemblyInfo.cs(19,12): error CS0579: “System.Reflection.AssemblyTitleAttribute”特性重复 [e:\workspace\Ter
a-Fin
der\TeraFinder.csproj]
E:\workspace\Tera-Finder\obj\Debug\net6.0-windows\TeraFinder.AssemblyInfo.cs(20,12): error CS0579: “System.Reflection.AssemblyVersionAttribute”特性重复 [e:\workspace\T
era-F
inder\TeraFinder.csproj]
E:\workspace\Tera-Finder\obj\Debug\net6.0-windows\TeraFinder.AssemblyInfo.cs(22,12): error CS0579: “System.Runtime.Versioning.TargetPlatformAttribute”特性重复 [e:\work
space
\Tera-Finder\TeraFinder.csproj]

**Comment by Manu098vm** [comment]
I can not replicate this issue. The github actions too doesn't report any build issue. Does it happen to you even with old commits? Since what commit did it start to drop build errors?
